name: Build Docker image
on: [push]

jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@master

      - name: Build Dockerfile.base image
        id: docker_build_base
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile.base
          push: false
          load: false
          tags: |
            malthe-prod-base

      - name: Build Dockerfile.prod image
        id: docker_build_prod
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile.prod
          push: false
          load: false
          tags: |
            malthe-prod
